-- AlterTable
ALTER TABLE `SESSION` ADD COLUMN `studyGroupID` INTEGER NULL;

-- CreateIndex
CREATE INDEX `SESSION_studyGroupID_idx` ON `SESSION`(`studyGroupID`);

-- AddForeignKey
ALTER TABLE `SESSION` ADD CONSTRAINT `SESSION_studyGroupID_fkey` FOREIGN KEY (`studyGroupID`) REFERENCES `STUDYGROUP`(`ID`) ON DELETE SET NULL ON UPDATE CASCADE;
