ALTER TABLE `STUDYGROUP` ADD COLUMN `inviteCode` CHAR(8) NULL;

UPDATE `STUDYGROUP`
SET `inviteCode` = UPPER(SUBSTRING(REPLACE(UUID(), '-', ''), 1, 8))
WHERE `inviteCode` IS NULL;

ALTER TABLE `STUDYGROUP` MODIFY `inviteCode` CHAR(8) NOT NULL;

CREATE UNIQUE INDEX `STUDYGROUP_inviteCode_key` ON `STUDYGROUP`(`inviteCode`);
