-- CreateTable
CREATE TABLE `PERSON` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(191) NOT NULL,
    `email` VARCHAR(191) NOT NULL,
    `firstName` VARCHAR(191) NOT NULL,
    `lastName` VARCHAR(191) NOT NULL,
    `password` VARCHAR(191) NOT NULL,
    `totalTimeStudied` INTEGER NOT NULL DEFAULT 0,
    `totalBrakeTime` INTEGER NOT NULL DEFAULT 0,
    `totalBrakes` INTEGER NOT NULL DEFAULT 0,
    `character` VARCHAR(191) NULL,

    UNIQUE INDEX `PERSON_username_key`(`username`),
    UNIQUE INDEX `PERSON_email_key`(`email`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SESSION` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `startDateTime` DATETIME(3) NOT NULL,
    `endDateTime` DATETIME(3) NULL,
    `brakeCount` INTEGER NOT NULL DEFAULT 0,
    `brakeTime` INTEGER NOT NULL DEFAULT 0,
    `subject` VARCHAR(191) NOT NULL,
    `personID` INTEGER NOT NULL,

    INDEX `SESSION_personID_idx`(`personID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `STUDYGROUP` (
    `ID` INTEGER NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(191) NOT NULL,
    `adminID` INTEGER NOT NULL,

    INDEX `STUDYGROUP_adminID_idx`(`adminID`),
    PRIMARY KEY (`ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `PARTOF` (
    `personID` INTEGER NOT NULL,
    `groupID` INTEGER NOT NULL,

    INDEX `PARTOF_groupID_idx`(`groupID`),
    PRIMARY KEY (`personID`, `groupID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SESSION` ADD CONSTRAINT `SESSION_personID_fkey` FOREIGN KEY (`personID`) REFERENCES `PERSON`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `STUDYGROUP` ADD CONSTRAINT `STUDYGROUP_adminID_fkey` FOREIGN KEY (`adminID`) REFERENCES `PERSON`(`ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PARTOF` ADD CONSTRAINT `PARTOF_personID_fkey` FOREIGN KEY (`personID`) REFERENCES `PERSON`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `PARTOF` ADD CONSTRAINT `PARTOF_groupID_fkey` FOREIGN KEY (`groupID`) REFERENCES `STUDYGROUP`(`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

